-- =============================================================================
-- seed 脚手架 PostgreSQL 建表脚本
-- =============================================================================
-- 依据：src/main/java/io/github/seed/entity 下的实体类反向生成，字段与实体逐一对应
--       命名遵循 MyBatis-Flex 默认的驼峰转下划线策略（configKey -> config_key）
-- 数据库：PostgreSQL（datasource 使用 currentSchema=public）
-- 测试数据：见同目录 seed-data.sql（须在本脚本之后执行）
--
-- 【重要】本脚本包含 DROP TABLE，会清空这些表的数据，仅用于开发/测试环境初始化
-- 【重要】主键为 GENERATED BY DEFAULT AS IDENTITY：
--       实体上的 @Id 未指定 keyType，MyBatis-Flex 默认 KeyType.None（不会回填主键），
--       因此主键必须由数据库生成，且允许脚本显式插入指定 id
-- =============================================================================

SET client_encoding = 'UTF8';

-- -----------------------------------------------------------------------------
-- 清理旧表（按依赖倒序，CASCADE 处理外键/索引残留）
-- -----------------------------------------------------------------------------
DROP TABLE IF EXISTS sys_operation_log CASCADE;
DROP TABLE IF EXISTS sys_sms_log CASCADE;
DROP TABLE IF EXISTS sys_login_log CASCADE;
DROP TABLE IF EXISTS sys_file_info CASCADE;
DROP TABLE IF EXISTS sys_role_permission CASCADE;
DROP TABLE IF EXISTS sys_user_role CASCADE;
DROP TABLE IF EXISTS sys_permission CASCADE;
DROP TABLE IF EXISTS sys_role CASCADE;
DROP TABLE IF EXISTS sys_user CASCADE;
DROP TABLE IF EXISTS sys_dict_data CASCADE;
DROP TABLE IF EXISTS sys_dict CASCADE;
DROP TABLE IF EXISTS sys_config CASCADE;
DROP TABLE IF EXISTS sys_dept CASCADE;

-- =============================================================================
-- 部门 sys_dept  <-  entity/sys/Dept.java  extends BaseLogicEntity
-- =============================================================================
CREATE TABLE sys_dept (
    id          bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name        varchar(30)  NOT NULL,
    parent_id   bigint       NOT NULL DEFAULT 0,
    sorts       integer      DEFAULT 0,
    deleted     smallint     NOT NULL DEFAULT 0,
    created_at  timestamp(3) NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at  timestamp(3)
);
COMMENT ON TABLE  sys_dept           IS '部门';
COMMENT ON COLUMN sys_dept.name      IS '部门名称';
COMMENT ON COLUMN sys_dept.parent_id IS '父级部门id，根部门为0';
COMMENT ON COLUMN sys_dept.sorts     IS '同级排序，升序';
COMMENT ON COLUMN sys_dept.deleted   IS '逻辑删除，0：否，默认；1：已删除';
CREATE INDEX idx_sys_dept_parent_id ON sys_dept (parent_id);

-- =============================================================================
-- 用户 sys_user  <-  entity/sys/User.java  extends BaseLogicEntity
-- =============================================================================
CREATE TABLE sys_user (
    id          bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    username    varchar(64)  NOT NULL,
    password    varchar(100),
    mobile      varchar(16),
    gender      char(1),
    birth_date  date,
    email       varchar(128),
    avatar      varchar(512),
    name        varchar(100),
    citizen_id  varchar(32),
    dept_id     bigint,
    status      smallint     NOT NULL DEFAULT 0,
    deleted     smallint     NOT NULL DEFAULT 0,
    created_at  timestamp(3) NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at  timestamp(3)
);
COMMENT ON TABLE  sys_user            IS '用户';
COMMENT ON COLUMN sys_user.username   IS '账号';
COMMENT ON COLUMN sys_user.password   IS '密码（BCrypt 哈希）';
COMMENT ON COLUMN sys_user.mobile     IS '手机号';
COMMENT ON COLUMN sys_user.gender     IS '性别，F：女，M：男，null：未知';
COMMENT ON COLUMN sys_user.birth_date IS '生日';
COMMENT ON COLUMN sys_user.email      IS '邮箱';
COMMENT ON COLUMN sys_user.avatar     IS '头像地址';
COMMENT ON COLUMN sys_user.name       IS '姓名';
COMMENT ON COLUMN sys_user.citizen_id IS '身份证号';
COMMENT ON COLUMN sys_user.dept_id    IS '部门id';
COMMENT ON COLUMN sys_user.status     IS '状态，0：正常；其它：锁定或者异常';
COMMENT ON COLUMN sys_user.deleted    IS '逻辑删除，0：否，默认；1：已删除';
-- 唯一约束只约束未删除的数据，软删除后账号可被重新使用（与 MyBatis-Flex 查询自动追加 deleted=0 的语义一致）
CREATE UNIQUE INDEX uidx_sys_user_username ON sys_user (username) WHERE deleted = 0;
CREATE INDEX idx_sys_user_mobile ON sys_user (mobile);
CREATE INDEX idx_sys_user_email  ON sys_user (email);
CREATE INDEX idx_sys_user_dept_id ON sys_user (dept_id);

-- =============================================================================
-- 角色 sys_role  <-  entity/sys/Role.java  extends BaseLogicEntity
-- =============================================================================
CREATE TABLE sys_role (
    id          bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    code        varchar(64)  NOT NULL,
    name        varchar(64)  NOT NULL,
    description varchar(255),
    deleted     smallint     NOT NULL DEFAULT 0,
    created_at  timestamp(3) NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at  timestamp(3)
);
COMMENT ON TABLE  sys_role             IS '角色';
COMMENT ON COLUMN sys_role.code        IS '角色标识';
COMMENT ON COLUMN sys_role.name        IS '角色名称';
COMMENT ON COLUMN sys_role.description IS '角色描述';
COMMENT ON COLUMN sys_role.deleted     IS '逻辑删除，0：否，默认；1：已删除';
CREATE UNIQUE INDEX uidx_sys_role_code ON sys_role (code) WHERE deleted = 0;

-- =============================================================================
-- 权限（菜单、按钮） sys_permission  <-  entity/sys/Permission.java  extends BaseLogicEntity
-- =============================================================================
CREATE TABLE sys_permission (
    id          bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    type        varchar(16)  NOT NULL,
    name        varchar(32)  NOT NULL,
    code        varchar(64),
    parent_id   bigint       NOT NULL DEFAULT 0,
    icon        varchar(128),
    path        varchar(255),
    component   varchar(255),
    description varchar(255),
    sorts       integer      DEFAULT 0,
    keep_alive  smallint     NOT NULL DEFAULT 0,
    visible     smallint     NOT NULL DEFAULT 1,
    deleted     smallint     NOT NULL DEFAULT 0,
    created_at  timestamp(3) NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at  timestamp(3)
);
COMMENT ON TABLE  sys_permission             IS '权限（菜单、按钮等）';
COMMENT ON COLUMN sys_permission.type        IS '权限类型，menu：菜单；button：按钮';
COMMENT ON COLUMN sys_permission.name        IS '名称';
COMMENT ON COLUMN sys_permission.code        IS '权限标识';
COMMENT ON COLUMN sys_permission.parent_id   IS '父节点id，根节点为0';
COMMENT ON COLUMN sys_permission.icon        IS '图标';
COMMENT ON COLUMN sys_permission.path        IS '路径';
COMMENT ON COLUMN sys_permission.component   IS '组件';
COMMENT ON COLUMN sys_permission.description IS '描述';
COMMENT ON COLUMN sys_permission.sorts       IS '同级排序，升序';
COMMENT ON COLUMN sys_permission.keep_alive  IS '是否路由缓冲，0：否；1：是';
COMMENT ON COLUMN sys_permission.visible     IS '是否显示，0：否；1：是，默认';
COMMENT ON COLUMN sys_permission.deleted     IS '逻辑删除，0：否，默认；1：已删除';
CREATE INDEX idx_sys_permission_parent_id ON sys_permission (parent_id);
CREATE INDEX idx_sys_permission_code      ON sys_permission (code);
CREATE INDEX idx_sys_permission_type      ON sys_permission (type);

-- =============================================================================
-- 角色-权限关联 sys_role_permission  <-  entity/sys/RolePermission.java  extends BaseEntity
-- （无逻辑删除字段）
-- =============================================================================
CREATE TABLE sys_role_permission (
    id            bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    permission_id bigint       NOT NULL,
    role_id       bigint       NOT NULL,
    created_at    timestamp(3) NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at    timestamp(3)
);
COMMENT ON TABLE  sys_role_permission               IS '角色关联权限';
COMMENT ON COLUMN sys_role_permission.permission_id IS '权限id，关联 sys_permission.id';
COMMENT ON COLUMN sys_role_permission.role_id       IS '角色id，关联 sys_role.id';
CREATE UNIQUE INDEX uidx_sys_role_permission ON sys_role_permission (role_id, permission_id);
CREATE INDEX idx_sys_role_permission_permission_id ON sys_role_permission (permission_id);

-- =============================================================================
-- 用户-角色关联 sys_user_role  <-  entity/sys/UserRole.java  extends BaseEntity
-- （无逻辑删除字段）
-- =============================================================================
CREATE TABLE sys_user_role (
    id         bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    user_id    bigint       NOT NULL,
    role_id    bigint       NOT NULL,
    created_at timestamp(3) NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at timestamp(3)
);
COMMENT ON TABLE  sys_user_role         IS '用户角色关联';
COMMENT ON COLUMN sys_user_role.user_id IS '用户id，关联 sys_user.id';
COMMENT ON COLUMN sys_user_role.role_id IS '角色id，关联 sys_role.id';
CREATE UNIQUE INDEX uidx_sys_user_role ON sys_user_role (user_id, role_id);
CREATE INDEX idx_sys_user_role_role_id ON sys_user_role (role_id);

-- =============================================================================
-- 字典 sys_dict  <-  entity/sys/Dict.java  extends BaseLogicEntity
-- =============================================================================
CREATE TABLE sys_dict (
    id          bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    type        varchar(64)  NOT NULL,
    name        varchar(64),
    description varchar(255),
    is_system   smallint     NOT NULL DEFAULT 0,
    deleted     smallint     NOT NULL DEFAULT 0,
    created_at  timestamp(3) NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at  timestamp(3)
);
COMMENT ON TABLE  sys_dict             IS '字典';
COMMENT ON COLUMN sys_dict.type        IS '字典类型';
COMMENT ON COLUMN sys_dict.name        IS '字典名称';
COMMENT ON COLUMN sys_dict.description IS '描述';
COMMENT ON COLUMN sys_dict.is_system   IS '系统内置的不允许页面修改。1：是；0：否';
COMMENT ON COLUMN sys_dict.deleted     IS '逻辑删除，0：否，默认；1：已删除';
CREATE UNIQUE INDEX uidx_sys_dict_type ON sys_dict (type) WHERE deleted = 0;

-- =============================================================================
-- 字典数据 sys_dict_data  <-  entity/sys/DictData.java  extends BaseLogicEntity
-- =============================================================================
CREATE TABLE sys_dict_data (
    id          bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    dict_id     bigint       NOT NULL,
    value       varchar(255) NOT NULL,
    label       varchar(64),
    description varchar(255),
    meta_data   text,
    sorts       integer      DEFAULT 0,
    deleted     smallint     NOT NULL DEFAULT 0,
    created_at  timestamp(3) NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at  timestamp(3)
);
COMMENT ON TABLE  sys_dict_data             IS '字典数据';
COMMENT ON COLUMN sys_dict_data.dict_id     IS '所属字典id，关联 sys_dict.id';
COMMENT ON COLUMN sys_dict_data.value       IS '数据值';
COMMENT ON COLUMN sys_dict_data.label       IS '标签名';
COMMENT ON COLUMN sys_dict_data.description IS '描述';
COMMENT ON COLUMN sys_dict_data.meta_data   IS '扩展数据';
COMMENT ON COLUMN sys_dict_data.sorts       IS '同级排序，升序';
COMMENT ON COLUMN sys_dict_data.deleted     IS '逻辑删除，0：否，默认；1：已删除';
CREATE INDEX idx_sys_dict_data_dict_id ON sys_dict_data (dict_id);
CREATE UNIQUE INDEX uidx_sys_dict_data ON sys_dict_data (dict_id, value) WHERE deleted = 0;

-- =============================================================================
-- 系统配置 sys_config  <-  entity/sys/Config.java  extends BaseLogicEntity
-- =============================================================================
CREATE TABLE sys_config (
    id           bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    config_key   varchar(64)  NOT NULL,
    description  varchar(255),
    config_value varchar(512) NOT NULL,
    is_encrypted smallint     NOT NULL DEFAULT 0,
    is_system    smallint     NOT NULL DEFAULT 0,
    deleted      smallint     NOT NULL DEFAULT 0,
    created_at   timestamp(3) NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at   timestamp(3)
);
COMMENT ON TABLE  sys_config              IS '系统配置';
COMMENT ON COLUMN sys_config.config_key   IS '标识';
COMMENT ON COLUMN sys_config.description  IS '描述';
COMMENT ON COLUMN sys_config.config_value IS '配置值';
COMMENT ON COLUMN sys_config.is_encrypted IS '值是否加密，1：是；0：否，默认';
COMMENT ON COLUMN sys_config.is_system    IS '是否系统内置，1：是；0：否，默认';
COMMENT ON COLUMN sys_config.deleted      IS '逻辑删除，0：否，默认；1：已删除';
CREATE UNIQUE INDEX uidx_sys_config_key ON sys_config (config_key) WHERE deleted = 0;

-- =============================================================================
-- 文件信息 sys_file_info  <-  entity/sys/FileInfo.java  extends BaseLogicEntity
-- =============================================================================
CREATE TABLE sys_file_info (
    id           bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    file_id      varchar(64)  NOT NULL,
    user_id      bigint,
    file_name    varchar(255),
    extension    varchar(32),
    mime_type    varchar(128),
    size         bigint,
    checksum     varchar(128),
    storage_path varchar(512),
    download_url varchar(1024),
    upload_at    timestamp(3),
    expire_at    timestamp(3),
    deleted      smallint     NOT NULL DEFAULT 0,
    created_at   timestamp(3) NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at   timestamp(3)
);
COMMENT ON TABLE  sys_file_info              IS '文件信息';
COMMENT ON COLUMN sys_file_info.file_id      IS '文件唯一标识';
COMMENT ON COLUMN sys_file_info.user_id      IS '上传者用户id';
COMMENT ON COLUMN sys_file_info.file_name    IS '文件名';
COMMENT ON COLUMN sys_file_info.extension    IS '文件后缀';
COMMENT ON COLUMN sys_file_info.mime_type    IS '文件媒体类型';
COMMENT ON COLUMN sys_file_info.size         IS '文件大小，单位：字节';
COMMENT ON COLUMN sys_file_info.checksum     IS '文件校验码';
COMMENT ON COLUMN sys_file_info.storage_path IS '保存路径';
COMMENT ON COLUMN sys_file_info.download_url IS '下载链接';
COMMENT ON COLUMN sys_file_info.upload_at    IS '上传时间';
COMMENT ON COLUMN sys_file_info.expire_at    IS '过期时间';
COMMENT ON COLUMN sys_file_info.deleted      IS '逻辑删除，0：否，默认；1：已删除';
CREATE UNIQUE INDEX uidx_sys_file_info_file_id ON sys_file_info (file_id) WHERE deleted = 0;
CREATE INDEX idx_sys_file_info_user_id   ON sys_file_info (user_id);
CREATE INDEX idx_sys_file_info_checksum  ON sys_file_info (checksum);

-- =============================================================================
-- 登录日志 sys_login_log  <-  entity/sys/LoginLog.java  extends BaseEntity
-- （无逻辑删除字段；result_code 为原始 int，非空）
-- =============================================================================
CREATE TABLE sys_login_log (
    id          bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    login_at    timestamp(3),
    user_id     bigint,
    username    varchar(64),
    type        varchar(32),
    result_code integer      NOT NULL DEFAULT 0,
    client_ip   varchar(64),
    location    varchar(255),
    user_agent  varchar(512),
    created_at  timestamp(3) NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at  timestamp(3)
);
COMMENT ON TABLE  sys_login_log             IS '登录日志';
COMMENT ON COLUMN sys_login_log.login_at    IS '登录时间';
COMMENT ON COLUMN sys_login_log.user_id     IS '用户id';
COMMENT ON COLUMN sys_login_log.username    IS '用户标识、如账号、手机号、邮箱等';
COMMENT ON COLUMN sys_login_log.type        IS '登录类型：sms、password';
COMMENT ON COLUMN sys_login_log.result_code IS '登录结果';
COMMENT ON COLUMN sys_login_log.client_ip   IS '客户端ip';
COMMENT ON COLUMN sys_login_log.location    IS '位置';
COMMENT ON COLUMN sys_login_log.user_agent  IS '浏览器标识';
CREATE INDEX idx_sys_login_log_user_id  ON sys_login_log (user_id);
CREATE INDEX idx_sys_login_log_login_at ON sys_login_log (login_at);

-- =============================================================================
-- 操作日志 sys_operation_log  <-  entity/sys/OperationLog.java  extends BaseEntity
-- （无逻辑删除字段）
-- =============================================================================
CREATE TABLE sys_operation_log (
    id              bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    description     varchar(255),
    user_id         bigint,
    type            varchar(32),
    operated_at     timestamp(3),
    cost_time       bigint,
    ref_module      varchar(64),
    ref_id          bigint,
    trace_id        varchar(64),
    request_uri     varchar(512),
    user_agent      varchar(512),
    http_method     varchar(16),
    client_ip       varchar(64),
    request_params  text,
    request_body    text,
    request_headers text,
    method          varchar(512),
    result_code     integer,
    result          text,
    error_strace    text,
    created_at      timestamp(3) NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at      timestamp(3)
);
COMMENT ON TABLE  sys_operation_log                 IS '操作日志';
COMMENT ON COLUMN sys_operation_log.description     IS '操作描述';
COMMENT ON COLUMN sys_operation_log.user_id         IS '用户id';
COMMENT ON COLUMN sys_operation_log.type            IS '操作类型';
COMMENT ON COLUMN sys_operation_log.operated_at     IS '操作时间';
COMMENT ON COLUMN sys_operation_log.cost_time       IS '耗时，单位：毫秒';
COMMENT ON COLUMN sys_operation_log.ref_module      IS '关联模块类型';
COMMENT ON COLUMN sys_operation_log.ref_id          IS '关联模块id';
COMMENT ON COLUMN sys_operation_log.trace_id        IS '请求轨迹id';
COMMENT ON COLUMN sys_operation_log.request_uri     IS '请求uri路径';
COMMENT ON COLUMN sys_operation_log.user_agent      IS '用户浏览器标识';
COMMENT ON COLUMN sys_operation_log.http_method     IS 'http方式';
COMMENT ON COLUMN sys_operation_log.client_ip       IS '客户端ip';
COMMENT ON COLUMN sys_operation_log.request_params  IS 'json格式的入参';
COMMENT ON COLUMN sys_operation_log.request_body    IS '请求体';
COMMENT ON COLUMN sys_operation_log.request_headers IS '请求头';
COMMENT ON COLUMN sys_operation_log.method          IS '执行的java方法';
COMMENT ON COLUMN sys_operation_log.result_code     IS '返回结果状态码';
COMMENT ON COLUMN sys_operation_log.result          IS 'json格式的返回值';
COMMENT ON COLUMN sys_operation_log.error_strace    IS '异常堆栈';
CREATE INDEX idx_sys_operation_log_user_id     ON sys_operation_log (user_id);
CREATE INDEX idx_sys_operation_log_operated_at ON sys_operation_log (operated_at);

-- =============================================================================
-- 短信日志 sys_sms_log  <-  entity/sys/SmsLog.java  extends BaseEntity
-- （无逻辑删除字段；status: 0待发送、1发送中、2发送成功、3发送失败
--   新增记录时只写 status=0、retry_count=0；
--   调度方抢占记录时 CAS 更新为 status=1，发送完成后回写 status、retry_count、send_at 与服务商返回信息；
--   发送失败未超过最大重试次数时 status 退回 0 等待重试，超过则置为 3 终态）
-- =============================================================================
CREATE TABLE sys_sms_log (
    id              bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    sms_no          varchar(32)  NOT NULL,
    scene           varchar(32),
    mobile          varchar(20)  NOT NULL,
    sign_name       varchar(64),
    template_code   varchar(64),
    template_params varchar(1024),
    content         varchar(1024),
    status          integer      NOT NULL DEFAULT 0,
    priority        integer      NOT NULL DEFAULT 0,
    retry_count     integer      NOT NULL DEFAULT 0,
    request_id      varchar(64),
    biz_id          varchar(64),
    result_code     varchar(64),
    result_message  varchar(512),
    send_at         timestamp(3),
    created_at      timestamp(3) NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at      timestamp(3)
);
COMMENT ON TABLE  sys_sms_log                 IS '短信日志';
COMMENT ON COLUMN sys_sms_log.sms_no          IS '短信业务编号，新增时服务端生成';
COMMENT ON COLUMN sys_sms_log.scene           IS '业务场景，如login、reset_password';
COMMENT ON COLUMN sys_sms_log.mobile          IS '手机号';
COMMENT ON COLUMN sys_sms_log.sign_name       IS '短信签名';
COMMENT ON COLUMN sys_sms_log.template_code   IS '短信模板编码，文本短信为空';
COMMENT ON COLUMN sys_sms_log.template_params IS '短信模板参数，json格式';
COMMENT ON COLUMN sys_sms_log.content         IS '短信文本内容，模板短信为空';
COMMENT ON COLUMN sys_sms_log.status          IS '发送状态：0待发送、1发送中、2发送成功、3发送失败';
COMMENT ON COLUMN sys_sms_log.priority        IS '优先级：0普通、1重要、2紧急，越大越优先发送';
COMMENT ON COLUMN sys_sms_log.retry_count     IS '发送失败次数，未超过最大重试次数时状态退回待发送';
COMMENT ON COLUMN sys_sms_log.request_id      IS '服务商请求id';
COMMENT ON COLUMN sys_sms_log.biz_id          IS '服务商回执id';
COMMENT ON COLUMN sys_sms_log.result_code     IS '服务商返回码';
COMMENT ON COLUMN sys_sms_log.result_message  IS '服务商返回描述，失败时为失败原因';
COMMENT ON COLUMN sys_sms_log.send_at         IS '最近一次发送时间';
CREATE UNIQUE INDEX uidx_sys_sms_log_sms_no ON sys_sms_log (sms_no);
-- 为后续基于数据库做发送频率限制与统计预留：按手机号+场景统计某时间段的发送量
CREATE INDEX idx_sys_sms_log_mobile_created_at ON sys_sms_log (mobile, created_at);
-- 调度取件：筛选可派发记录后按「优先级降序、主键升序」取一批，索引与该排序一致
CREATE INDEX idx_sys_sms_log_dispatch ON sys_sms_log (status, priority DESC, id);
CREATE INDEX idx_sys_sms_log_scene_created_at  ON sys_sms_log (scene, created_at);
CREATE INDEX idx_sys_sms_log_status            ON sys_sms_log (status);
